### ISSUE TITLE
Unable to login to SMB shares.

### ISSUE THREAD

**Issue by technoicon** [ahaenggli/AzureAD-LDAP-wrapper#12]
Can't access SMB shares via LDAP Auth.

Connect everything to LDAP docker container.
Can login via DSM using LDAP details (azure ad details).
Try to navigate to SMB share \\synologynas\
Askes for username and password.
Enter:
username@domain.com.au
Pass.
Get message username and password is incorrect.  even though using the same as DSN login that just worked.

**Expected behavior**
To be able to login to SMB share with LDAP credentials.

**Comment by ahaenggli** [comment]
Is samba enabled? Did you you allow the user to use samba in its (or its groups) permissions?
if both is yes: Are there some more infos in the log output? If not, please set the env var `LDAP_DEBUG` to true for the container, try the samba access again and check the log output again

**Comment by technoicon** [comment]
Yeah, SMB is enabled and allowed for the LDAP user and groups.
I've also added the user to the folder permissions.
Getting logs now.

**Comment by technoicon** [comment]
Attached is the logs.
[LDAP Logs.csv](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/files/8064764/LDAP.Logs.csv)

**Comment by ahaenggli** [comment]
The log doesn't look like samba is accessing the ldap server. You would have much more entries. 
Check your samba setting and its permissions again. 
On my DSM 7 it looks like this:
- env var `DSM7` is set to true in the docker container
![image](https://user-images.githubusercontent.com/23347180/154018856-cdee712f-c22c-4017-b877-b15df473206d.png)

- File Services > smb is enabled
![image](https://user-images.githubusercontent.com/23347180/154018236-c112ca64-7eff-4ed6-80b3-a4840426fcf5.png)

- LDAP-User > has some folder permissions (read/write) and the use of SMB-Application is allowed
![image](https://user-images.githubusercontent.com/23347180/154017782-4a230add-b806-4837-a5a2-198689999742.png)
- No local user with the same name as my ldap-user
![image](https://user-images.githubusercontent.com/23347180/154018022-11e86f3f-9b4b-4337-bec2-481b33b758be.png)

**Comment by snk-nick** [comment]
Getting the same issue - users can log into the DSM web interface without issue but cannot access any SMB shares. Running DSM7, groups all synced up and can log into the web interface no problems but SMB authentication isn't working. 

- DSM7 var is set to true/ports correctly set.
- User has access to SMB application. 
- User has access to fileshare/can access it via the DSM web interface.
- DEBUG is on, but don't see anything in the logs to indicate any kind of SMB activity.

**Comment by ahaenggli** [comment]
I'm pretty clueless right now. It just works for me... Maybe my setup is just simpler than yours....
Can you give me more details?
- Is the domain in the format "domain.tld" or "com.domain.tld"?
- How many users and groups are synchronized?
- Does a user have only 1 or more groups?
- Are you using Windows for samba access? 
- If so, Win10 or Win11?
- Are your devices azure joined devices? Are you using local users or AD users?

Maybe I can somehow recreate the problem with the information and debug it that way.

My setup is like this:
- Domain in format "domain.tld"
- 2 users, 2 groups (default users and one from azure called "devs")
- I use mainly the group users@domain.tld (there SMB is allowed, access for music/photos/videos shared folder)
- Group devs@domain.tld (there is also SMB allowed, access for music/photos/videos-shared folder and web/docker/scans shared folder) 
- Win11 with local user, connection to \\nas\ I do with username@domain.tld

**Comment by snk-nick** [comment]
Appreciate you taking a look!

- My domain is domain.net.au
- It's brought over 5 users and 12 groups, mostly Azure defaults.
- User has several groups and I've made sure they have access, I've even given the user access directly.
- Windows 10, latest build.
- Azure AD joined/Intune managed device

DSM is on the latest version as well (7.0.1-42218 Update 2)

The only other thing I can think of that I found slightly abnormal was that when I joined the NAS to the LDAP server it warned me there was a duplicate group - the 'users' group. Azure doesn't actually list this group anywhere in AAD but apparently it has one and it synced across. Synology has one as a default group as well, but I'm not using either of them here.

**Comment by technoicon** [comment]
I'm wondering if our domain is causing issues because it's domain.tld.tld
for example domain.com.au.

**Comment by snk-nick** [comment]
Hrm possible but I use 3 and 4 length domains all the time and it's never been an issue. Seems to work everywhere else and does allow logging into DSM no problems.

**Comment by snk-nick** [comment]
Well I can see where the problem is at least... jumping into the filesystem of the container and looking at azure.json, the sambaNTPassword fields aren't being filled when logging into the DSM interface. 

The only one actually filled is the account I used to connect to the LDAP server. The rest are X's. 

`/app $ cat .cache/azure.json | grep sambaNTPassword
    "sambaNTPassword": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "sambaNTPassword": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "sambaNTPassword": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "sambaNTPassword": "1F30FC99EDC994B44ABAFAB570ABA489",
    "sambaNTPassword": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",`

So the one filled is the account used to join the LDAP server. The other four are the other accounts in AAD, two of which have been logged into the DSM interface and two which have not. Logging in to the test machine as the user who joined the LDAP server, everything works fine.

Interestingly checking the logs for the container when I log into one of those accounts I see: 

`server.js server.bind joe@domain.net.au Saving NT password hash for user  uid=joe,cn=users,dc=domain,dc=net,dc=au`

So it's logging it as successfully saved but that's not making it to the file. I removed the volume and restarted the container to rule out Synology permission issues with the mapped volume and it behaves the same way.

**Comment by ahaenggli** [comment]
oh, I see. Let's assume there are those three users in the AAD:
alice@domain.net.au, bob@domain.net.au and joe@domain.net.au

alice, bob and joe can only "see" (and modify) their own passwords, not the others. If they would make a ldapsearch in a console, it would be a security risk. So you need to join LDAP server with a not existing user from the env var `LDAP_BINDUSER`.

I absolutely have to throw an error when writing the file instead of the info - I'll add that in the next version.

**Comment by snk-nick** [comment]
Annnd you literally have that in the documentation. Sorry for wasting your time, I only read the entry down the bottom for the ENV variables and missed the mention that you have to use that for SAMBA where you list it under step 3.

Totally on me, but to prevent further idiots from making the same mistake maybe change "Optional" to "Optional unless you wish to access SMB shares" or similar.

The hashes are now showing up now upon logging into DSM, but they still refuse to pass through to the shares via Windows - I have to hit "more choices" then enter the account name and password in there before it will authenticate. That expected behaviour or is something else broken?

**Comment by technoicon** [comment]
That's about expected behaviour.

I would love it to authenticate with our windows auth that setup to azure
but I read in another thread that's not possible yet?
If this happens it would be like SSO.

**Comment by snk-nick** [comment]
Damn, generally Windows will try and use the current username and password to connect to a network share before looking to use something else. Guess it's not in the right format or something else going on.

**Comment by ahaenggli** [comment]
@snk-nick 
I just added that part of the documentation yesterday after your posts. So you have not missed anything. All good :)

@technoicon
Yep, that's the expected behaviour. Windows attempts to authenticate with samba. Windows will not access the ldap-wrapper directly.
So, users have to type - at least once - their passwords to access the shares.

As soon as it is an azure joined device or the device is in an AD, it will try the current username (without password, it uses tokens).
For a working SSO you would need an Active Directory with Kerberos or something like that (p.e. hybrid-setup, meaning only AAD is not enough). To support a real SSO I would have to implement a whole AD Server (or find and integrate one, which can use the ldap entries)

@both
The user format doesn't matter:
- username@domain.tld
- azuread\username@domain.tld
- azuread\username
- username

will all work equalliy, as tested in issue #7 ([this post](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/issues/7#issuecomment-892656464))

After some tests with wrong user/passwords the password-prompt keeps showing for me too. That's when I always clean up the entries on my (Win11-) computer in 'System Control' > 'Credential Manager' > 'Windows credentials'. Afterwards I add an entry manually and reboot. Hope that helps you too:
<img src="https://user-images.githubusercontent.com/23347180/154835318-5a15b58e-ab5b-47a6-bb94-f9e5a9429557.png" width=50% height=50%>

**Comment by ahaenggli** [comment]
I wanted to ask if everything is working in the meantime? Or do you still have the same problems? 
If everything is ok, I would like to close the issue :)

**Comment by gili98** [comment]
I have the same issue - users can log into the DSM web interface without issue but cannot access any SMB shares.
Running DSM7, groups all synced up and can log into the web interface no problems but SMB authentication isn't working.

DSM7 var is set to true/ports correctly set.
User has access to SMB application.
User has access to fileshare/can access it via the DSM web interface.
DEBUG is on, but don't see anything in the logs to indicate any kind of SMB activity.
