### ISSUE TITLE
Home Directory value modification

### ISSUE THREAD

**Issue by marc-odp** [ahaenggli/AzureAD-LDAP-wrapper#34]
Hi,
I wanted to change the home directory of a user but after 30 minutes it went back to the previous value.
It seems that the program is creating the home folder value ? I searched on Azure and didn't find any field like that and I found the code below.
Is it possible to put this as an option (parameter) so we could create and maintain our own value for home directory ?
![image](https://user-images.githubusercontent.com/17361839/190453764-8e9126cd-7cce-456e-b282-aeefdb04bcd2.png)

**Comment by ahaenggli** [comment]
The easiest way would be to use a customizer. To do this, you can create a js file and map it to the container as `./customizer/ldap_customizer.js`. 
You can add, delete, or overwrite any attribute of an LDAP entry in this file.
The following example shows how to set the homeDirectory to `/home/{uidNumber}` instead of `/home/{uid}`

```javascript
'use strict';
const config = require('../config');
const helper = require('../helper');

var customizer = {};

// overwrite the home directory
customizer.ModifyLDAPUser = function (ldapuser, azureuser) {
    helper.log("customizer", "ModifyLDAPUser", "called");
    if (ldapuser.hasOwnProperty("homeDirectory")) {
        ldapuser.homeDirectory = "/home/" + ldapuser.uidNumber,
    }
    return ldapuser;
};

module.exports = customizer;
```

More examples can be found [here](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/tree/main/customizer). Attention, if you already use the DSM7 environment variable (uidNumber and gidNumber as number instead of text): Your customizer is preferred and the DSM7 customizer is no longer loaded. To use both, you would have to copy the DSM7 [customizer file](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/blob/main/customizer/customizer_DSM7_IDs_string2int.js), paste your extension there and map this file into the conatainer as `./customizer/ldap_customizer.js`.

**Comment by marc-odp** [comment]
> The easiest way would be to use a customizer. To do this, you can create a js file and map it to the container as `./customizer/ldap_customizer.js`.

That is great. However I am confused about this path : ./customizer/ldap_customizer.js
Do you mean /app/customizer/ldap_customizer.js ?
The leading dot seems to make a problem with docker...

**Comment by ahaenggli** [comment]
Oooops, you're absolutely right. Sorry! It should be `/app/customizer/ldap_customizer.js`

**Comment by marc-odp** [comment]
I noticed also :
`ldapuser.homeDirectory = "/home/" + ldapuser.uidNumber;`
instead of 
`ldapuser.homeDirectory = "/home/" + ldapuser.uidNumber,`
Semicolon at the end...
It works now. Thank you !
