### ISSUE TITLE
Allow Accounts with 2FA to go trough

### ISSUE THREAD

**Issue by schmitch** [ahaenggli/AzureAD-LDAP-wrapper#35]
Hello, I love your wrapper, however since we use 2fa more and more on our accounts it would be great if there would be a option to let users without a successful 2fa flow to still authenticate.
I know that the ROPG flow does not support it, **but** there are ways around it.
We also use macs with JAMFNOW which actually supports something like that: https://docs.jamf.com/jamf-connect/2.0.0/administrator-guide/Multifactor_Authentication.html

What they do is simple, they use two AzureAD Apps:

1. App for the Login which uses the ROPG flow, if the ErrorCode for MFA is triggered ([AADSTS50076](https://docs.microsoft.com/de-de/azure/active-directory/develop/reference-aadsts-error-codes)) (https://www.jamf.com/blog/how-to-azure-conditional-access-and-jamf-connect/)
2. App usses client_credentials Flow (via secret or cert) and will return the bindings even if MFA ErrorCode is triggered

**Comment by ahaenggli** [comment]
Hello. Thx for your feedback and the additional information about JAMFNOW and how they handle MFA! 
Look’s like I could get it working without even a second app as I don't need effective tokens for the users.

There are several ways to define MFA and therefore more than one ErrorCode... I will document some tests here so that I can find them again if necessary.

### Per-user MFA
MFA could be [enabled individually](https://learn.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-userstates) for each user. A possible workaround seems to be the [trusted IPs feature](https://learn.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-mfasettings#trusted-ips), which allows to disable MFA for some IPs, but this feature requires Azure AD Premium. ErrorCode for this way of MFA is AADSTS50079.

### Security defaults
[Security defaults](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults) seems to be the only ways for customers using the free Azure AD plan to [enable multi-factor authentication](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-mfa-get-started#free-option) in their whole environment. ErrorCode for this way of MFA is AADSTS50076. I haven't found any workarounds here.

### Conditional Access
[Conditional Access](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-all-users-mfa) can be used to require MFA for some or all the users. This is the most flexible way to activate MFA, but it is a premium feature. ErrorCode for this way of MFA is AADSTS50079, too. The settings allows to exclude certain apps. As a simple workaround, the app used by the LDAP-wrapper can be excluded:
- Add a URL in the app (e.g. "https://localhost") 
![grafik](https://user-images.githubusercontent.com/23347180/190912948-56826e2b-b64c-41e7-b2b0-9bab7e43e5f0.png)
- The App can now be selected in the exclude list
![grafik](https://user-images.githubusercontent.com/23347180/190912999-de1ae723-0a66-46ec-968a-4e763eef6a11.png)

### Other ErrorCodes
The Microsoft [documentation](https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes#aadsts-error-codes) mentions further error codes related to multi-factor authentication. For example, AADSTS50072 if a user has not (yet) added a second factor, AADSTS50078 if the second factor has expired, AADSTS53004/AADSTS53010 due to risk, and others for different types of MFA errors.

### Conclusion
On a first attempt, the error codes AADSTS50076 and AADSTS50079 could be considered successful logins, as the error code AADSTS50126 should be triggered by invalid credentials.

**Comment by ahaenggli** [comment]
A first attempt is available in the docker dev tag. Any test and use is very welcome :)
To enable the new feature, set the env var `GRAPH_IGNORE_MFA_ERRORS` to true.

**Comment by ahaenggli** [comment]
The changes are now also available in the latest version (v1.8.2).
