### ISSUE TITLE
MFA Conditional Access

### ISSUE THREAD

**Issue by tfonfara** [ahaenggli/AzureAD-LDAP-wrapper#58]
Hi,

I tried to follow the [Bypass MFA](https://ahaenggli.github.io/AzureAD-LDAP-wrapper/configuration/bypass-mfa/) guide, added `https://localhost` as redirect uri, also followed [Common Conditional Access policy: Require MFA for all users](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-all-users-mfa) to setup a new policy for the ldap wrapper. In the end I ended up in the policy with "Include: All cloud apps" and "Exclude: my ldap wrapper". However, if I try to do a login request, I receive error `AADSTS50076`.

In my docker config I have the following vars set:
```
TZ: ...
AZURE_APP_ID: ...
AZURE_TENANTID: ...
AZURE_APP_SECRET: ...
LDAP_DOMAIN: ...
LDAP_BASEDN: ...
LDAP_BINDUSER: ...
LDAP_ALLOWCACHEDLOGINONFAILURE: "false"
LDAP_ANONYMOUSBIND: "all"
GRAPH_FILTER_GROUPS: ""
```

Is there any additional setting, that is required in order to get this working?
(Setting `GRAPH_IGNORE_MFA_ERRORS` is working fine, but ideally I would like to get this working with the conditional access).

Thank you in advance!

**Comment by agonza05** [comment]
Hello @tfonfara, just sharing my experience as I had a similar issue where I configured everything correctly and still got AADSTS50076 error. In the end, for me the issue was as documented [here](https://ahaenggli.github.io/AzureAD-LDAP-wrapper/troubleshooting/#why-are-personal-microsoft-accounts-not-supported) that AzureAD will not work with identities for "normal" users (live.com, outlook.com, etc.). Not sure if it is the same for you but it might save you some troubleshooting / googling time.

**Comment by tfonfara** [comment]
Thanks @agonza05, unfortunately this is not the issue in my case, all users are company accounts.

**Comment by ahaenggli** [comment]
The AADSTS50076 error indicates that you are using the security defaults. [You can use either security defaults or Conditional Access policies, but you can't use both at the same time.](https://learn.microsoft.com/en-us/microsoft-365/business-premium/m365bp-turn-on-mfa?view=o365-worldwide&tabs=secdefaults) 
My guess is that your rules are not used because the security defaults are enabled.

**Comment by myevit** [comment]
I have exactly the same issue. My guess is that you are trying to login with azure global administrator account. I have created conditional access and able to login with test user (that have mfa) without problem. smb share start working too.
