### ISSUE TITLE
Azure AD-joined devices having trouble accessing shares

### ISSUE THREAD

**Issue by q20** [ahaenggli/AzureAD-LDAP-wrapper#7]
Hello again!

I'm currently setting up a small infrastructure and have issues accessing data over SMB from Windows. Users can log in to DSM with the M365 credentials (not full email address, though - just the username before the @ symbol).
So I can confirm the sync between M365 and the docker container is working perfectly.

Do you have any idea why the logged on user credentials are not being accepted by the Synology over Windows Explorer?
I have made sure to set up your LDAP service with dc=example,dc=com matching the Azure AD primary domain.

Can this be achieved? Right now I think I'm going to have to train users to input their username and pass in Windows Explorer manually and save. Which is not ideal and not transparent.

Thanks!

**Comment by q20** [comment]
Perhaps the LDAP server could respond to what Windows attempts to authenticate with:
AZUREAD\userexamplecom

USERDOMAIN=AzureAD
USERDOMAIN_ROAMINGPROFILE=AzureAD
USERNAME=userexamplecom

If USERNAME could be mapped to LDAP UID, would the user authenticate properly?

Am I making sense?  ;p

**Comment by q20** [comment]
So, as a workaround, I'm going to run the following script per-user:

`$Address=( whoami.exe /UPN )
$Name=$Address.Split("@")[0]
net use T: \\server\share /user:$Name /savecred /persistent:yes
`

This will use the prefix of the user's email address to connect to a share on the Synology.

**Comment by ahaenggli** [comment]
Sorry, but I don't understand the problem/question...
Users should be able to login on the DSM either with "username" or "username@domain.tld", as written as in the Name column seen here:
![grafik](https://user-images.githubusercontent.com/23347180/126906810-93551ad6-4dc5-436e-aeca-83faf97c8b0c.png)
Both (with or without domain) works if you use the same domain for the ldap setup as the primary domain in your azure-tenant (at least for the two setups I'm using it).

To access a share from Windows, you have to enable Samba for some users (or groups) by allow the 'SMB' Application for those.
Then you can simply acces it, example '\\\my-syno-nas\home' and type username (with or without domain) and the password in the "enter network credentials" dialog. 
Windows authenticates to synology-samba not this ldap-wrapper. Samba and Windows use the cached password hash in sambaNTPassword from the ldap-wrapper. Thats why each user has to login in DSM before using a share in Windows. (Same after changing a password, the user must login in DSM again so it can be used for the file share too.)

In DSM 7 there are some problems with group permissions from others than the default users' group.
The problem is caused by the userIds and groupIds. In DSM 6.2 it seems, they must be strings while in DSM 7 it seems, they have to be numbers.
To fix the data type, map [this file](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/blob/main/customizer/customizer_DSM7_IDs_string2int.js) as '/app/customizer/ldap_customizer.js' in your docker container:
![grafik](https://user-images.githubusercontent.com/23347180/126906962-693257f5-eab8-48b2-a7e3-63986d1e04c2.png)

**Comment by q20** [comment]
Hi!

Yup, users are able to log in to DSM using their M365 credentials; this is a non-issue. What I have discovered, though, is that Windows Explorer will attempt to use current credentials to access a network resource (in this case a share on the Synology). As the Azure-joined users have a username formatted as AZUREAD\FirstnameSurnameExampleCom, this username cannot possibly be passed through transparently to the Synology and the user is therefore prompted to enter user and pass.

I was hoping that your LDAP might be configured to also accept the AZUREAD-formatted username. Somehow. ;p

**Comment by ahaenggli** [comment]
I don't think Single Sign On will work with just LDAP :( 
Users have to type - at least once - their passwords to access shares.
Windows attempts to authenticate with samba. Windows will not access the ldap-wrapper directly. 
I think for SSO you would need an Active Directory or something like that...

You can even map the shares with UPN and/or azuread-prefix:
```
$Address=( whoami.exe /UPN ) 
echo $Address 
net use T: \\server\Backup /persistent:yes /user:$Address  
```
works on my azure-ad joined devices as well as the azuread-formated upn
```
$Address = ("azuread\"+ ( whoami.exe /UPN ) )
echo $Address
net use T: \\server\Backup /persistent:yes /user:$Address
```
and the azuread-formated username:
```$Address=( whoami.exe /UPN )
$Name="azuread\"+$Address.Split("@")[0]
echo $Name
net use T: \\server\Backup /persistent:yes /user:$Name
```

You can also try the other way and set 'LDAP_DEBUG' to true in the ldap-wrapper env vars.
The ldap-wrapper will not recieve an login attemp before the credentials-dialog is shown in Windows. 
Is it different in your setup? If so, could you send me the log? I'll gladly try adding a fix :)

**Comment by q20** [comment]
I think we can close this issue; I was hoping SSO, or pass-through authentication would take place automatically.
Anyhoo, as long as I can get users to access data on the Synology using their same user/pass combo, we're good.

Again, thanks so much for this incredible integration.  : )
