### ISSUE TITLE
Suggestion for the  radius by using AzureLDAP on Synology

### ISSUE THREAD

**Issue by yuhongwei380** [ahaenggli/AzureAD-LDAP-wrapper#72]
The current usage is to log in to Synology and then  save the password(hash) to a file after verification; then the radius client can perform wlan authentication.

Is it possible that when we perform wlan verification directly through the Synology radius client, we can directly verify it with azure. If the verification is correct, it will be saved directly to the password file. Maybe this is a good direction?

You can modify it directly to this solution without considering it, such as adding a button or a module field to allow users to fill in. Then use different verification rules after filling in?

**Comment by yuhongwei380** [comment]
and how to donate for alipay ? I only have alipay

**Comment by ahaenggli** [comment]
No, because Radius unfortunately does not forward the user password (hash) to the LDAP server. The user logs on to Radius. The user does not interact directly with the LDAP wrapper. Synology Radius loads the user and password hash from the LDAP wrapper and compares the values itself with the user input. The username and password are never forwarded to the LDAP server. The LDAP server can therefore not verify them with Azure.

**Comment by yuhongwei380** [comment]
So sad for hear that , it is a pity;
